### ISSUE TITLE
Error creating new post template 

### ISSUE THREAD

**Issue by chrisofspades** [haacked/aboard-feedback#1]
I tried to create a new post template and received a 404 error after clicking the "Add Saved Template" button. I had a title for the template but no body.

**Comment by haacked** [comment]
Did it work when you tried it with both a title and body?

**Comment by chrisofspades** [comment]
Yes, it works with title and body.

**Comment by haacked** [comment]
Cool, I'll be deploying a fix soon. Unfortunately I haven't set up deployment slots so the site will be down a bit.

**Comment by haacked** [comment]
There's a fix deployed. Thanks for the report!
