### ISSUE TITLE
Using Gmail's "plus naming" email addresses might be breaking something...

### ISSUE THREAD

**Issue by jnpwly** [haacked/aboard-feedback#3]
Kia ora, Phil, from NZ!

I trust you are well, and that your family are also staying healthy and safe. So, Aboard looks interesting... really interesting! Congrats on getting a "minimum viable product" up and running!

I tried signing up just now, using the email address "blah.blah+getaboard.net@gmail.com" -- that is, using Gmail's "plus naming" facility. But, it looks like this triggered an error 😭 -- see Request ID: 00-01e1986b17ccc04ba192107a5e28054e-78b16b174983ce46-00. Hopefully knowing what I was doing will be of help here.

Ngā mihi,
   Jon

**Comment by haacked** [comment]
Hi Jon,

Could you try it again? There was another bug I accidentally deployed.

Regarding the + in your email, that shouldn't be a problem except for one
thing. Do you plan to use gmail to authenticate to aboard (using Google
Auth?). If so, Aboard tries to match up the email provided by gmail with
the one in the invitation. It might not match up. I'd be curious for you to
try it because this might be a case I need to handle.

Phil

**Comment by jnpwly** [comment]
Kia ora. Yes, it worked this time -- I see the "Thank you! We will be in touch soon" message.

I probably would use Google Auth, and so I see how the + in the email might confuse things. Don't see an immediate way around this. There was one website I tried to use recently-ish that insisted on taking out the "+blah.blah" from the email address I entered, so that was a) clever, if they needed to ensure it would match up with an external auth provider; but also b) annoying, as I would still want emails from them to be filterable (which is what I use the + addresses for.)

But, it looks like the immediate problem has been fixed. 👏

**Comment by jnpwly** [comment]
Follow up: An invite was sent to my supplied email address (blah.blah+getaboard.net@gmail.com). I attempted to use the Google Auth method to create an account on Aboard, but, obvs the email addresses used did not match up -- "This Board is invite only. Ask your friend to make sure your email "blah.blah@gmail.com" is on the guest list." See 00-39b0a9ae735f1947bc39216f3015edf3-c73299a818d1ea44-00.

**Comment by haacked** [comment]
Thanks for following up! I better fix this.

**Comment by haacked** [comment]
I fixed these issues. Thanks for the report!

**Comment by jnpwly** [comment]
@haacked -- you are welcome! 😁

(Did request 00-a26746a6d0ca8647ace735dd8498086c-bffc8755fe043a4c-00 break something else...? I tried "signing up" for a new invite, using the same blah.blah+getaboard.net@gmail.com address that I used previously.)

**Comment by jnpwly** [comment]
... but I can sign up with Gmail with a "plus naming" address 👍

**Comment by haacked** [comment]
Ha ha! Yes, you've uncovered another apparent bug. But glad you got in with your gmail + address.

**Comment by haacked** [comment]
Fixed that bug now too.

**Comment by jnpwly** [comment]
Coding machine! 😉
