### ISSUE TITLE
"Internal Server Error"

### ISSUE THREAD

**Issue by yooakim** [haacked/aboard-feedback#4]
When I try to open the webpage https://getaboard.net/ I end up with an internal server error:
![image](https://user-images.githubusercontent.com/862546/79191794-b1cc4500-7e27-11ea-8f42-aa313e12a5f3.png)

I am using Microsoft Edge 81.0.416.53 on Windows 10.

**Comment by haacked** [comment]
Thanks for the report. I fixed this a while ago. Let me know if it still happens for you.
