### ISSUE TITLE
Layout issue on `~\directory` page

### ISSUE THREAD

**Issue by jnpwly** [haacked/aboard-feedback#5]
It's minor... but there's an issue with the layout on the `~/directory` page:

![image](https://user-images.githubusercontent.com/10701621/79523968-7776d800-80b3-11ea-81e4-d7fb49e1ca94.png)

At *smaller* page sizes, the content of the card fits within the card, and the image takes up more of the available page; as the viewport is made bigger, counterintuitively, the image becomes smaller, and then the contents start overlapping the object's boundary. There's also a point where the icons wrap oddly *and* the hamburger menu is shown *with* the icons. ¯\_(ツ)_/¯

It's probably a reasonably easy fix... but it would take me aaages to figure that out. My CSS-fu is just too woeful!

**Comment by haacked** [comment]
Yeah, it seems to only be a problem when there's only one person on a page.

**Comment by haacked** [comment]
This has been fixed. Let me know if you see any other issues.
